### ISSUE TITLE
Overcoat 4.0

### ISSUE THREAD

**Issue by sodastsai** [Overcoat/Overcoat#113]
- [x] Add CI support f32b881 6f68148
- [x] Use [AFNetworking 3.x](https://github.com/AFNetworking/AFNetworking/milestones/3.0.0) 94dbd0b
  + [x] Drop support of `NSURLConnection` 94dbd0b
- [x] Drop support of Mantle 1.x 3138846
- [x] Support to ReactiveCocoa 3.x/4.x #110
- [x] ~~Support to Bolts Tasks~~ _(Move to 4.1 or future)_
- [x] Split PromiseKit and ReactiveCocoa support to another framework/podspec
- [x] Carthage Support #95 4b7a5c2
- [x] ~~Model request serializer #83~~ _(Move to 4.1 or future)_
- [x] Response Class Matcher for same URL but different HTTP methods #64 f4e82e6
- [ ] Rewrite documentation

**Comment by sergey-sportsetter** [comment]
:+1:

**Comment by sodastsai** [comment]
Mantle 1.x dropped by 3d30c83

**Comment by chrisdhaan** [comment]
Updates sound awesome! Can't wait.

**Comment by sodastsai** [comment]
The first beta `4.0.0-beta.1` is available in CocoaPods and has a git tag for Carthage now.
Please test it :)

and Happy Holidays. (So if there are some issues in the beta, I may fix it after the holidays. But still, you're welcome to submit PRs for it)

**Comment by bsameh** [comment]
@sodastsai Happy holidays! :)
